

<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\tModLoader.targets" />
	
        <PropertyGroup>
            <AssemblyName>TerrariaAmbience</AssemblyName>
            <LangVersion>latest</LangVersion>
	    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        </PropertyGroup>
    
	<PropertyGroup>
	    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
	    </PropertyGroup>

	    <ItemGroup>
		<Publicize Include="FNA" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	    </ItemGroup>
	
	    <ItemGroup>
            <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
                <PrivateAssets>all</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            </PackageReference>
        </ItemGroup>
	
	
        <ItemGroup>
            <Reference Include="TerrariaAmbienceAPI">
            <HintPath>lib\TerrariaAmbienceAPI.dll</HintPath>
            </Reference>
        </ItemGroup>
	
	
</Project>